### ISSUE TITLE
Report panic: runtime error: index out of range

### ISSUE THREAD

**Issue by m-lukas** [homeport/havener#101]
Executing the command upgrade with the --config flag causes the following error.
According to @HeavyWombat, the bug is probably in /internal/hvnr/diffs.go:75.

**Error Message:**

runtime error: index out of range

Stacktrace:
```goroutine 1 [running]:
runtime/debug.Stack(0xc0000e3690, 0x2140fbe, 0x11)
	/usr/local/go/src/runtime/debug/stack.go:24  0x9d
github.com/homeport/havener/internal/cmd.exitWithErrorAndIssue(0x216b748, 0x31, 0x232dd40, 0x2edf600)
	/Users/lukas.mueller/Projects/havener/internal/cmd/common.go:106  0x287
github.com/homeport/havener/internal/cmd.Execute.func1()
	/Users/lukas.mueller/Projects/havener/internal/cmd/root.go:58  0x171
panic(0x1fba5c0, 0x2edf600)
	/usr/local/go/src/runtime/panic.go:522  0x1b5
github.com/homeport/havener/internal/hvnr.ShowHelmReleaseDiff(0xc000150150, 0x7, 0xc0001501b0, 0xe, 0xc0003ec3c0, 0x3c, 0x40, 0x0, 0xc0003ae000, 0x32756d0)
	/Users/lukas.mueller/Projects/havener/internal/hvnr/diffs.go:75  0x769
github.com/homeport/havener/internal/cmd.UpgradeViaHavenerConfig(0x7ffeefbffad7, 0x1b, 0xe, 0x7ffeefbffad7)
	/Users/lukas.mueller/Projects/havener/internal/cmd/upgrade.go:112  0x4fe
github.com/homeport/havener/internal/cmd.glob..func9(0x2eeade0, 0xc0003cc0e0, 0x0, 0x2, 0x0, 0x0)
	/Users/lukas.mueller/Projects/havener/internal/cmd/upgrade.go:56  0x64
github.com/spf13/cobra.(*Command).execute(0x2eeade0, 0xc0003cc040, 0x2, 0x2, 0x2eeade0, 0xc0003cc040)
	/Users/lukas.mueller/Projects/golang/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826  0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x2eea8e0, 0x21cc5a0, 0x21cddd8, 0x109326f)
	/Users/lukas.mueller/Projects/golang/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914  0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lukas.mueller/Projects/golang/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/homeport/havener/internal/cmd.Execute()
	/Users/lukas.mueller/Projects/havener/internal/cmd/root.go:66  0x60
main.main()
	/Users/lukas.mueller/Projects/havener/cmd/havener/main.go:42  0xcd
```

**Comment by qu1queee** [comment]
working on this via https://github.com/homeport/havener/tree/qu1queee/issue-101
