### ISSUE TITLE
Report panic: runtime error: index out of range - havener upgrade

### ISSUE THREAD

**Issue by m-lukas** [homeport/havener#171]
When running the following command `havener upgrade --config examples/mongodb-config.yml`, I get the following error message:

runtime error: index out of range

__Stacktrace:__
```goroutine 1 [running]:
runtime/debug.Stack(0xc000d27698, 0x2171d2a, 0x11)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/debug/stack.go:24  0x9d
github.com/homeport/havener/internal/cmd.exitWithErrorAndIssue(0x219c5aa, 0x31, 0x2363d80, 0x2f86140)
	/home/travis/gopath/src/github.com/homeport/havener/internal/cmd/root.go:150  0x226
github.com/homeport/havener/internal/cmd.Execute.func1()
	/home/travis/gopath/src/github.com/homeport/havener/internal/cmd/root.go:63  0x171
panic(0x1fe6c80, 0x2f86140)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/panic.go:522  0x1b5
github.com/homeport/havener/internal/hvnr.ShowHelmReleaseDiff(0xc0003b0f80, 0x7, 0xc0003b0fc0, 0xe, 0xc0000f40a0, 0x4c, 0x50, 0x0, 0x1fbe6c0, 0xc00027fe30)
	/home/travis/gopath/src/github.com/homeport/havener/internal/hvnr/diffs.go:75  0x769
github.com/homeport/havener/internal/cmd.UpgradeViaHavenerConfig(0x7ffeefbff9d1, 0x1b, 0xe, 0x7ffeefbff9d1)
	/home/travis/gopath/src/github.com/homeport/havener/internal/cmd/upgrade.go:106  0x2f2
github.com/homeport/havener/internal/cmd.glob..func10(0x2f91da0, 0xc0002de0e0, 0x0, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/homeport/havener/internal/cmd/upgrade.go:55  0x64
github.com/spf13/cobra.(*Command).execute(0x2f91da0, 0xc0002de040, 0x2, 0x2, 0x2f91da0, 0xc0002de040)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826  0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x2f91620, 0x21fd888, 0xc000768ed0, 0x102b271)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914  0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/homeport/havener/internal/cmd.Execute()
	/home/travis/gopath/src/github.com/homeport/havener/internal/cmd/root.go:71  0x60
main.main()
	/home/travis/gopath/src/github.com/homeport/havener/cmd/havener/main.go:51  0xe5
```

__Further information:__
```
# helm ls --all mongodb
NAME    REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE
mongodb 1               Tue Aug 13 13:32:57 2019        DEPLOYED        mongodb-7.1.1   4.0.12          mongodb
# 
# havener version
havener version v1.0.0, Go version go1.12.7 darwin/amd64
```

**Comment by HeavyWombat** [comment]
Should be fixed by https://github.com/homeport/havener/commit/6823667734adc1492e07b9bd4dcb477482cd95b1.
