### ISSUE TITLE
Yet another havener top panic

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/havener#205]
**Describe the bug**
A `panic` during `havener` command `top` in a rather small terminal (181x36).

**To Reproduce**
_unknown_

**Expected behavior**
No panics.

**Screenshots**
```
panic: assignment to entry in nil map

goroutine 2697 [running]:
github.com/homeport/havener/pkg/havener.(*Hvnr).TopDetails.func2(0xc000a0f400, 0xc00076d140, 0xc0011b8180, 0xc000710020)
	/home/travis/gopath/src/github.com/homeport/havener/pkg/havener/top.go:211 +0x572
created by github.com/homeport/havener/pkg/havener.(*Hvnr).TopDetails
	/home/travis/gopath/src/github.com/homeport/havener/pkg/havener/top.go:190 +0xc34
```

**Additional context**
n/a

**Comment by HeavyWombat** [comment]
Duplicate of #204
