### ISSUE TITLE
And another panic during top command

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/havener#217]
Following panic occurred:
```
panic: runtime error: index out of range

goroutine 19879 [running]:
github.com/homeport/havener/pkg/havener.parseProcLoadAvg(0x0, 0x0, 0x0, 0x200, 0x0)
	/home/travis/gopath/src/github.com/homeport/havener/pkg/havener/top.go:284 +0x197
github.com/homeport/havener/pkg/havener.(*Hvnr).TopDetails.func3(0xc001185950, 0xc0005d9bc0, 0xc000047ec0, 0xc00127e6e0, 0x0, 0x0, 0x0, 0x0, 0xc002811de0, 0x9, ...)
	/home/travis/gopath/src/github.com/homeport/havener/pkg/havener/top.go:255 +0x5ea
created by github.com/homeport/havener/pkg/havener.(*Hvnr).TopDetails
	/home/travis/gopath/src/github.com/homeport/havener/pkg/havener/top.go:218 +0xd2b
```

**Comment by HeavyWombat** [comment]
Duplicate of #204.
