### ISSUE TITLE
Need a better message format when deployment failed

### ISSUE THREAD

**Issue by edwardstudy** [homeport/havener#36]
When deployment failed, havener returned this message

```
binaries/havener-darwin-amd64  deploy --config examples/tomcat-deployment.yml
⠙ Creating Helm Release for tomcat-releaseMessage: Unable to create and initialize the tunnel, Error: could not find tiller
```

It contained two sentences. 

Maybew we can split by `:` or other format:
```
⠙ Creating Helm Release for tomcat-release: Message: Unable to create and initialize the tunnel, Error: could not find tiller
```

**Comment by edwardstudy** [comment]
Reopened it. I pulled develop branch ad built new binaries and got same message format.

And new releasse got worse:

```
$ ./havener-kube-1.10-helm-2.10-darwin-amd64 deploy --config examples/tomcat-deployment.yml
 ⠙ Creating Helm Release for tomcat-release                                                                                                                                                            7 secpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cfd4d6]

goroutine 1 [running]:
github.com/homeport/havener/vendor/k8s.io/helm/pkg/helm.(*Client).InstallReleaseFromChart(0x0, 0xc0004f8d20, 0xc0007e98b0, 0x6, 0xc000dc1ab0, 0x7, 0x7, 0x0, 0xc00070fa38, 0x10c66c7)
	/home/travis/gopath/src/github.com/homeport/havener/vendor/k8s.io/helm/pkg/helm/client.go:91 +0x36
github.com/homeport/havener/pkg/havener.DeployHelmRelease(0xc0007e9890, 0xe, 0xc0007e98b0, 0x6, 0xc0007e98d0, 0xd, 0x28, 0xc0007e9990, 0x5, 0x8, ...)
	/home/travis/gopath/src/github.com/homeport/havener/pkg/havener/helm.go:145 +0x542
github.com/homeport/havener/internal/cmd.glob..func2(0x327ff40, 0xc0007df9c0, 0x0, 0x2)
	/home/travis/gopath/src/github.com/homeport/havener/internal/cmd/deploy.go:95 +0x4fe
github.com/homeport/havener/vendor/github.com/spf13/cobra.(*Command).execute(0x327ff40, 0xc0007df920, 0x2, 0x2, 0x327ff40, 0xc0007df920)
	/home/travis/gopath/src/github.com/homeport/havener/vendor/github.com/spf13/cobra/command.go:757 +0x2cc
github.com/homeport/havener/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x32808c0, 0x0, 0x327fa80, 0xc00070ff58)
	/home/travis/gopath/src/github.com/homeport/havener/vendor/github.com/spf13/cobra/command.go:843 +0x2fd
github.com/homeport/havener/vendor/github.com/spf13/cobra.(*Command).Execute(0x32808c0, 0x10053b0, 0xc00009c058)
	/home/travis/gopath/src/github.com/homeport/havener/vendor/github.com/spf13/cobra/command.go:791 +0x2b
github.com/homeport/havener/internal/cmd.Execute()
	/home/travis/gopath/src/github.com/homeport/havener/internal/cmd/root.go:51 +0x2d
main.main()
	/home/travis/gopath/src/github.com/homeport/havener/cmd/havener/main.go:26 +0x20
```

Did I miss anything?

**Comment by HeavyWombat** [comment]
I am sorry, but we failed to reproduce your issue. This is how it looks for us:
![image](https://user-images.githubusercontent.com/1979133/49437400-bb698580-f7bb-11e8-8a6a-cdc379e21ac2.png)

One thing you could try is to run `make clean` first, since this cleans the Go cache. One other thing is to add `-a` to `go build` to enforce a full rebuild.

**Comment by edwardstudy** [comment]
@HeavyWombat, thank you. I'll check it.

**Comment by edwardstudy** [comment]
Hi, @HeavyWombat. My situation was that my cluster hadn't tiller deploy, so `Unable to create and initialize the tunnel, Error: could not find tiller` from first message was OK except output format.

But in v0.7-alpha, I didn't know why it caused memory error when invoke InstallReleaseFromChart. And it was after connecting tiller.

**Comment by HeavyWombat** [comment]
@edwardstudy Ok, thanks for the update. Any chance you can compile a list of steps I can repeat to reproduce the state you had when encountering the problem?

Also, I try to publish a new release soon, which has commit 5666557a220c696172142a67ca45cfbf2bda2a36 in it to handle any unexpected panic situation to display a well formatted exit message.

**Comment by edwardstudy** [comment]
OK, @HeavyWombat. I just finished #20 about tiller init and ran it well from rebasing master branch. So it was a good news.
 
This panic only happened in v0.7-alpha:
```
$ git checkout v0.7-alpha
$ make clean
$ make build
$ binaries/havener-kube-1.10-helm-2.10-darwin-amd64 deploy --config examples/tomcat-deployment.yml -v
[DEBUG] Looking for config file...
[DEBUG] Reading config file...
[DEBUG] Unmarshaling config file...
[DEBUG] Creating helm chart(s)...
[DEBUG] Processing overrides section...
[DEBUG] Marshaling overrides section...
[DEBUG] Reading kube config file...
[DEBUG] Locating helm chart location...
 ⠏ Creating Helm Release for tomcat-release                                                                                                                                                            4 sec[DEBUG] Loading chart in namespace tomcat...
[DEBUG] Getting helm client...
 ⠸ Creating Helm Release for tomcat-release                                                                                                                                                            5 sec[DEBUG] Installing release in namespace tomcat...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1dc2826]

goroutine 1 [running]:
github.com/homeport/havener/vendor/k8s.io/helm/pkg/helm.(*Client).InstallReleaseFromChart(0x0, 0xc4203dd560, 0xc42098f608, 0x6, 0xc420abfa98, 0x7, 0x7, 0x0, 0xc4209cfa20, 0x10c7ee7)
	/Volumes/journey/workspace/src/github.com/homeport/havener/vendor/k8s.io/helm/pkg/helm/client.go:91 +0x36
github.com/homeport/havener/pkg/havener.DeployHelmRelease(0xc42098f5e0, 0xe, 0xc42098f608, 0x6, 0xc42098f630, 0xd, 0x28, 0xc42098f6d0, 0x5, 0x8, ...)
	/Volumes/journey/workspace/src/github.com/homeport/havener/pkg/havener/helm.go:145 +0x58e
github.com/homeport/havener/internal/cmd.glob..func2(0x2f923e0, 0xc42082b1d0, 0x0, 0x3)
	/Volumes/journey/workspace/src/github.com/homeport/havener/internal/cmd/deploy.go:95 +0x62c
github.com/homeport/havener/vendor/github.com/spf13/cobra.(*Command).execute(0x2f923e0, 0xc42082b0e0, 0x3, 0x3, 0x2f923e0, 0xc42082b0e0)
	/Volumes/journey/workspace/src/github.com/homeport/havener/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/homeport/havener/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2f92d60, 0x23bf585, 0xc4209cff38, 0xc4209cff40)
	/Volumes/journey/workspace/src/github.com/homeport/havener/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/homeport/havener/vendor/github.com/spf13/cobra.(*Command).Execute(0x2f92d60, 0x0, 0x1)
	/Volumes/journey/workspace/src/github.com/homeport/havener/vendor/github.com/spf13/cobra/command.go:791 +0x2b
github.com/homeport/havener/internal/cmd.Execute()
	/Volumes/journey/workspace/src/github.com/homeport/havener/internal/cmd/root.go:51 +0x31
main.main()
	/Volumes/journey/workspace/src/github.com/homeport/havener/cmd/havener/main.go:26 +0x20
```

**Comment by edwardstudy** [comment]
Closed it because latest code had fixed it.
